test_sequence:
  "1":
    planning_time: 7.0
    robot_poses:
      length: 13
      "0": [0,0.733,1.098,0,1.310,-0.785]
      "1": [2.921,1.206,0.318,0,1.617,0.566]
      "2": [2.921,1.311,0.491,0,1.339,0.566]
      "3": [1.471,0.513,1.423,0,1.204,-0.887]
      "4": [1.471,0.721,1.492,0,0.927,-0.886]
      "5": [0.786,0.867,0.886,0,1.387,-0.776]
      "6": [0,0,0,0,0,0]
      "7": [3.089,1.082,0.531,0,1.529,0.734]
      "8": [3.089,1.221,0.652,0,1.269,0.734]
      "9": [-0.03,0.429,1.344,0.003,1.368,-0.782]
      "10": [-0.03,0.602,1.501,0.003,1.038,-0.782]
      "11": [1.326,0.759,0.869,0,1.514,-2.604]
      "12": [1.326,0.995,1.070,0,1.077,-2.604]
    robot_sequence:
      length: 27
      nonrestrictive_pipeline: irrt_avoid #irrt_avoid, dirrt, dirrt
      nonrestrictive_planner: irrta #irrta, dirrt_paper, multigoal_ssm_test
      "0":
        description: "open gripper"
        type: 2
        pct: 50
        after_human_task: -1
        start_delay: 0.0
      "1":
        description: "go to start position"
        type: 0
        goal: 0
        after_human_task: -1
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
      "2":
        description: "go to pick perch over piston"
        type: 0
        goal: 1
        after_human_task: -1
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
      "3":
        description: "go to pick piston"
        type: 0
        goal: 2
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "4":
        description: "close gripper"
        type: 1
        pct: 0
        after_human_task: -1
        start_delay: 0.0
      "5":
        description: "raise back to pick perch over piston"
        type: 0
        goal: 1
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "6":
        description: "go to place perch over piston fixture"
        type: 0
        goal: 3
        after_human_task: -1
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
      "7":
        description: "go to place piston in fixture"
        type: 0
        goal: 4
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "8":
        description: "open gripper"
        type: 2
        pct: 30
        after_human_task: -1
        start_delay: 0.0
      "9":
        description: "raise to perch over piston"
        type: 0
        goal: 3
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      # "9":
      #   description: "back away from workspace"
      #   type: 0
      #   goal: 5
      #   after_human_task: -1
      #   start_delay: 0.0
      #   pipeline: irrt_avoid
      #   planner: irrta
      "10":
        description: "go to perch over the next piston"
        type: 0
        goal: 7
        after_human_task: -1
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
      "11":
        description: "go to pick piston"
        type: 0
        goal: 8
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "12":
        description: "close gripper"
        type: 1
        pct: 0
        after_human_task: -1
        start_delay: 0.0
      "13":
        description: "raise back to pick perch over piston"
        type: 0
        goal: 7
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "14":
        description: "go to place perch over piston fixture"
        type: 0
        goal: 3
        after_human_task: 7
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
      "15":
        description: "go to place piston in fixture"
        type: 0
        goal: 4
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "16":
        description: "open gripper"
        type: 2
        pct: 100
        after_human_task: -1
        start_delay: 0.0
      "17":
        description: "raise to perch over piston"
        type: 0
        goal: 3
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "18":
        description: "go to pick crankshaft"
        type: 0
        goal: 9
        after_human_task: -1
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
      "19":
        description: "pick crankshaft"
        type: 0
        goal: 10
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "20":
        description: "close gripper"
        type: 1
        pct: 0
        after_human_task: -1
        start_delay: 0.0
      "21":
        description: "raise crankshaft"
        type: 0
        goal: 9
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "22":
        description: "go to place crankshaft"
        type: 0
        goal: 11
        after_human_task: -1
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
      "23":
        description: "lower crankshaft"
        type: 0
        goal: 12
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "24":
        description: "open gripper"
        type: 2
        pct: 100
        after_human_task: -1
        start_delay: 0.0
      "25":
        description: "back away"
        type: 0
        goal: 11
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "26":
        description: "back away from workspace"
        type: 0
        goal: 6
        after_human_task: -1
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
    human_sequence:
      length: 21
      start_pose: []  
      simulated_switch_times: [0.0]  
      show_human_rate: 50
      "0":
        description: "right arm start pose"
        after_robot_task: 0
        after_human_task: -1
        start_delay: 0.0
        reach_target: [-0.2,0.8,-0.1]
        arm: "right"
        check_pos: false
      "1":
        description: "left arm start pose"
        after_robot_task: 0
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.2,0.8,-0.1]
        arm: "left"
        check_pos: false
      "2":
        description: "pick up the connecting rod"
        after_robot_task: 1
        after_human_task: -1
        start_delay: 0.0
        reach_target: [-0.31,0.25,0.05]
        arm: "right"
        check_pos: true
      "3":
        description: "bring connecting rod near to assembly area"
        after_robot_task: 1
        after_human_task: -1
        start_delay: 2.0
        reach_target: [-0.3,0.65,0.05]
        arm: "right"
        check_pos: true
      "4":
        description: "ensure the left arm is out of the way"
        after_robot_task: 1
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.2,0.85,-0.1]
        arm: "left"
        check_pos: false
      "5":
        description: "place connecting rod in piston after robot places piston"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 0.0
        reach_target: [-0.0,0.4,0.1]
        arm: "right"
        check_pos: true
      "6":
        description: "rest right arm"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 0.0
        reach_target: [-0.2,0.8,-0.1]
        arm: "right"
        check_pos: false
      "7":
        description: "pick up the pin"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.2,0.5,0.00]
        end_delay: 2.0
        arm: "left"
        check_pos: true
      "8":
        description: "insert pin through piston and rod"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 2.0
        reach_target: [-0.0,0.4,0.05]
        end_delay: 0.0
        arm: "left"
        check_pos: true
      "9":
        description: "put the piston rod assembly into the block"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 2.0
        reach_target: [-0.2,0.4,0.05]
        end_delay: 0.0
        arm: "left"
        check_pos: true
      "10":
        description: "ensure the left arm is out of the way"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.2,0.8,-0.1]
        arm: "left"
        check_pos: false
      # "11":
      #   description: "ensure the right arm is out of the way"
      #   after_robot_task: 8
      #   after_human_task: -1
      #   start_delay: 0.0
      #   reach_target: [-0.2,0.8,-0.1]
      #   arm: "right"
      "11":
        description: "pick up connecting rod 2"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 0.0
        reach_target: [-0.39,0.25,0.05]
        arm: "right"
        check_pos: true
      "12":
        description: "bring connecting rod 2 near to assembly area"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 2.0
        reach_target: [-0.3,0.65,0.2]
        arm: "right"
        check_pos: true
      "13":
        description: "ensure the left arm is out of the way"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.2,0.8,-0.1]
        arm: "left"
        check_pos: false
      "14":
        description: "place connecting rod 2 in piston after robot places piston"
        after_robot_task: 18
        after_human_task: -1
        start_delay: 0.0
        reach_target: [-0.0,0.4,0.1]
        arm: "right"
        check_pos: true
      "15":
        description: "rest right arm"
        after_robot_task: 18
        after_human_task: -1
        start_delay: 0.0
        reach_target: [-0.2,0.8,-0.1]
        arm: "right"
        check_pos: false
      "16":
        description: "pick up pin 2"
        after_robot_task: 18
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.2,0.5,0.00]
        end_delay: 0.0
        arm: "left"
        check_pos: true
      "17":
        description: "insert pin 2 through piston and rod"
        after_robot_task: 18
        after_human_task: -1
        start_delay: 2.0
        reach_target: [-0.0,0.4,0.05]
        end_delay: 0.0
        arm: "left"
        check_pos: true
      "18":
        description: "put the piston rod assembly 2 into the block"
        after_robot_task: 18
        after_human_task: -1
        start_delay: 2.0
        reach_target: [-0.2,0.4,0.05]
        end_delay: 0.0
        arm: "left"
        check_pos: true
      "19":
        description: "ensure the left arm is out of the way"
        after_robot_task: 18
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.2,0.8,-0.1]
        arm: "left"
        check_pos: false
      "20":
        description: "ensure the right arm is out of the way"
        after_robot_task: 18
        after_human_task: -1
        start_delay: 0.0
        reach_target: [-0.2,0.8,-0.1]
        arm: "right"
        check_pos: false
