test_sequence:
  robot_poses:
    length: 4
    "0": [0,0.8,0.8,0,0.8,0]
    "1": [0,0.6,0.8,0,0.8,0]
    "2": [2.8,0.6,0.8,0,0.8,0]
    "3": [2.8,0.8,0.8,0,0.8,0]
    "4": [2.8,0.8,0.8,0,0.8,0]
  robot_sequence:
    length: 8
    "0":
      description: "go to pick perch over piston"
      type: 0
      goal: 1
      after_human_task: -1
      start_delay: 0.0
    "1":
      description: "go to pick piston"
      type: 0
      goal: 0
      after_human_task: -1
      start_delay: 0.0
    "2":
      description: "close gripper"
      type: 1
      after_human_task: -1
      start_delay: 0.0
    "3":
      description: "raise back to pick perch over piston"
      type: 0
      goal: 1
      after_human_task: -1
      start_delay: 0.0
    "4":
      description: "go to place perch over piston fixture"
      type: 0
      goal: 2
      after_human_task: -1
      start_delay: 0.0
    "5":
      description: "open gripper"
      type: 2
      after_human_task: -1
      start_delay: 0.0
    "6":
      description: "go to place piston in fixture"
      type: 0
      goal: 3
      after_human_task: -1
      start_delay: 0.0
    "7":
      description: "raise to perch over piston"
      type: 0
      goal: 2
      after_human_task: -1
      start_delay: 0.0
    "8":
      description: "back away from workspace"
      type: 0
      goal: 4
      after_human_task: -1
      start_delay: 0.0
    "9":
      description: "go to perch over the next piston"
      type: 0
      goal: 4
      after_human_task: -1
      start_delay: 0.0
  human_sequence:
    length: 3
    start_pose: []
    "0":
      description: "pick up the connecting rod"
      after_robot_task: -1
      after_human_task: -1
      start_delay: 0.0
      reach_target: [-0.35,0.1,0.05]
      arm: "right"
    "1":
      description: "bring connecting rod near to assembly area"
      after_robot_task: -1
      after_human_task: -1
      start_delay: 2.0
      reach_target: [-0.05,0.4,0.1]
      arm: "right"
    "2":
      description: "place connecting rod in piston"
      after_robot_task: 8
      after_human_task: -1
      start_delay: 0.0
      reach_target: [-0.0,0.4,0.1]
      arm: "right"
    "3":
      description: "pick up the pin"
      after_robot_task: 8
      after_human_task: -1
      start_delay: 0.0
      reach_target: [0.1,0.3,0.00]
      end_delay: 2.0
      arm: "left"
    "4":
      description: "insert pin through piston and rod"
      after_robot_task: 8
      after_human_task: -1
      start_delay: 0.0
      reach_target: [-0.0,0.4,0.05]
      end_delay: 2.0
      arm: "left"
    "5":
      description: "put the piston rod assembly into the block"
      after_robot_task: 8
      after_human_task: -1
      start_delay: 0.0
      reach_target: [-0.2,0.4,0.2]
      end_delay: 2.0
      arm: "left"
