warp:
  repulsion: 0.02
  attraction: 0.01
  table_repulsion: 0.02
  smooth_steps: 2
  iterations: 2
  table_tolerance: 0.07
  connection_tol: 0.99
  cycle_time: 0.1
  direct_path_attraction: 0.0001
  connection_min_dist: 0.3