test_sequence:
  "1":
    add_collision_box: true
    collision_box_origin_xyz_wxyz_dims: [0.399758,0.4,1.075,-0,0.707214,-0.707,0,0.4,0.3,0.15]
    workcell_transform: [0.0,0.0,1.0,0.707,0,0,-0.707]
    planning_time: 7.0
    robot_positions:
      length: 13
      "0": [0.4,0.0,0.11,0.000273793,-0.382499,0.923956,-0.000113345]
      "1": [-0.453,0.102,0.11,5.09227e-05,0.923651,-0.383235,-0.000291919]
      "2": [-0.453,0.102,0.0152,7.85397e-05,0.923641,-0.383259,-0.000273132]
      "3": [0.035,0.352377,0.11,-0.000762618,0.924224,-0.381849,-0.000229237]
      "4": [0.035,0.352358,0.02,-0.000800416,0.924053,-0.382264,-0.000278614]
      "5": [0,0,0,0,0,0]
      "6": [0,0,0,0,0,0]
      "7": [-0.453,0.024,0.11,-6.80575e-05,0.923651,-0.383235,0.000191966]
      "8": [-0.453,0.024,0.015,-3.9832e-05,0.923648,-0.383243,0.000132972]
      "9": [0.35,-0.01,0.16,0.000852539,-0.366922,0.930251,0.00123287]
      "10": [0.35,-0.01,0.06,0.000788811,-0.366483,0.930424,0.00102364]
      "11": [0.1,0.4,0.16,0.000163487,0.923303,0.384073,-0.000121469]
      "12": [0.1,0.4,0.01,0.000100051,0.923319,0.384035,-8.02571e-05]
    robot_positions_at:
      length: 13
      "0": [0.000120783,-0.399879,1.11,0.000113495,0.382728,0.923861,-0.000273731]
      "1": [-0.05,0.452894,1.11,0.000250186,0.00044629,1,0.000158797]
      "2": [-0.05,0.452894,0.925,0.000250186,0.00044629,1,0.000158797]
      "3": [0.32,-0.034883,1.11,0.0,0.70710678118,-0.70710678118,0.0]
      "4": [0.32,-0.034883,1.05,0.0,0.70710678118,-0.70710678118,0.0]
      "5": [0,0,0,0,0,0]
      "6": [0,0,0,0,0,0]
      "7": [-0.05,0.531,1.11,0.000250186,0.00044629,1,0.000158797]
      "8": [-0.05,0.531,0.925,0.000250186,0.00044629,1,0.000158797]
      "9": [-0.0098913,-0.349897,1.16,0.000250186,0.00044629,1,0.000158797]
      "10": [-0.0098913,-0.349897,1.06,0.000250186,0.00044629,1,0.000158797]
      "11": [0.32,-0.099849,1.16,0.000250186,0.00044629,1,0.000158797]
      "12": [0.32,-0.099849,1.05,0.000250186,0.00044629,1,0.000158797]
    robot_poses:
      length: 13
      "0": [2.2995,-1.88062,2.0405,-1.73022,1.56967,-1.51353]
      "1": [0.0775783,-2.04998,2.13965,-1.66006,1.56922,-0.0761876]
      "2": [0.0770145,-2.0277,1.80206,-1.34477,1.56969,-0.0761556]
      "3": [1.43319,-1.77553,1.96457,-1.75981,1.5702,-3.00352]
      "4": [1.43304,-1.78948,1.86925,-1.65054,1.57026,-3.00356]
      "5": [0.786,0.867,0.886,0,1.387,-0.776]
      "6": [1.5707963267949, -2.44346095279206, 2.44346095279206,-1.5707963267949, 1.5707963267949, 0]
      "7": [0.0649718,-1.90778,2.05828,-1.72077,1.56924,-0.0635828]
      "8": [0.0646554,-1.90379,1.73034,-1.39737,1.57,-0.0637762]
      "9": [2.23252,-1.9587,2.17867,-1.79035,1.57069,-2.23093]
      "10": [2.23212,-1.98242,2.01564,-1.60392,1.57061,-2.23089]
      "11": [1.54829,-1.72915,2.01738,-1.85807,1.57035,-1.54688]
      "12": [1.54791,-1.76457,1.84974,-1.65556,1.57022,-1.54674]
    robot_sequence:
      length: 27
      nonrestrictive_pipeline: irrt_avoid #irrt_avoid, dirrt, dirrt
      nonrestrictive_planner: irrta #irrta, dirrt_paper, multigoal_ssm_test
      "0":
        description: "open gripper"
        type: 2
        pct: 50
        after_human_task: -1
        start_delay: 0.0
      "1":
        description: "go to start position"
        type: 0
        goal: 0
        after_human_task: -1
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
      "2":
        description: "go to pick perch over piston"
        type: 0
        goal: 1
        after_human_task: -1
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
      "3":
        description: "go to pick piston"
        type: 0
        goal: 2
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "4":
        description: "close gripper"
        type: 1
        pct: 0
        after_human_task: -1
        start_delay: 0.0
      "5":
        description: "raise back to pick perch over piston"
        type: 0
        goal: 1
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "6":
        description: "go to place perch over piston fixture"
        type: 0
        goal: 3
        after_human_task: -1
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
      "7":
        description: "go to place piston in fixture"
        type: 0
        goal: 4
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "8":
        description: "open gripper"
        type: 2
        pct: 30
        after_human_task: -1
        start_delay: 0.0
      "9":
        description: "raise to perch over piston"
        type: 0
        goal: 3
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      # "9":
      #   description: "back away from workspace"
      #   type: 0
      #   goal: 5
      #   after_human_task: -1
      #   start_delay: 0.0
      #   pipeline: irrt_avoid
      #   planner: irrta
      "10":
        description: "go to perch over the next piston"
        type: 0
        goal: 7
        after_human_task: -1
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
      "11":
        description: "go to pick piston"
        type: 0
        goal: 8
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "12":
        description: "close gripper"
        type: 1
        pct: 0
        after_human_task: -1
        start_delay: 0.0
      "13":
        description: "raise back to pick perch over piston"
        type: 0
        goal: 7
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "14":
        description: "go to place perch over piston fixture"
        type: 0
        goal: 3
        after_human_task: 7
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
      "15":
        description: "go to place piston in fixture"
        type: 0
        goal: 4
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "16":
        description: "open gripper"
        type: 2
        pct: 100
        after_human_task: -1
        start_delay: 0.0
      "17":
        description: "raise to perch over piston"
        type: 0
        goal: 3
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "18":
        description: "go to pick crankshaft"
        type: 0
        goal: 9
        after_human_task: -1
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
      "19":
        description: "pick crankshaft"
        type: 0
        goal: 10
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "20":
        description: "close gripper"
        type: 1
        pct: 0
        after_human_task: -1
        start_delay: 0.0
      "21":
        description: "raise crankshaft"
        type: 0
        goal: 9
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "22":
        description: "go to place crankshaft"
        type: 0
        goal: 11
        after_human_task: -1
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
      "23":
        description: "lower crankshaft"
        type: 0
        goal: 12
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "24":
        description: "open gripper"
        type: 2
        pct: 100
        after_human_task: -1
        start_delay: 0.0
      "25":
        description: "back away"
        type: 0
        goal: 11
        after_human_task: -1
        start_delay: 0.0
        pipeline: ompl
        planner: BiTRRT
      "26":
        description: "back away from workspace"
        type: 0
        goal: 6
        after_human_task: -1
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
    human_sequence:
      length: 21
      start_pose: []  
      simulated_switch_times: [0.0]  
      show_human_rate: 50
      "0":
        description: "right arm start pose"
        after_robot_task: 0
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.8,0.2,0.9] #[-0.2,0.8,0.9]
        arm: "right"
        check_pos: false
      "1":
        description: "left arm start pose"
        after_robot_task: 0
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.8,-0.2,0.9] #[0.2,0.8,0.9]
        arm: "left"
        check_pos: false
      "2":
        description: "pick up the connecting rod"
        after_robot_task: 1
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.1,0.31,1.05] #[-0.31,0.25,1.05]
        arm: "right"
        check_pos: true
      "3":
        description: "bring connecting rod near to assembly area"
        after_robot_task: 1
        after_human_task: -1
        start_delay: 2.0
        reach_target: [0.65,0.3,1.05] #[-0.3,0.65,1.05]
        arm: "right"
        check_pos: true
      "4":
        description: "ensure the left arm is out of the way"
        after_robot_task: 1
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.85,-0.2,0.9] #[0.2,0.85,0.9]
        arm: "left"
        check_pos: false
      "5":
        description: "place connecting rod in piston after robot places piston"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.32,0,1.1] #[-0.0,0.4,1.1]
        arm: "right"
        check_pos: true
      "6":
        description: "rest right arm"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.8,0.2,0.9] #[-0.2,0.8,0.9]
        arm: "right"
        check_pos: false
      "7":
        description: "pick up the pin"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.32,-0.3,1.00] #[0.2,0.5,1.00]
        end_delay: 2.0
        arm: "left"
        check_pos: true
      "8":
        description: "insert pin through piston and rod"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 2.0
        reach_target: [0.32,0.0,1.05] #[-0.0,0.4,1.05]
        end_delay: 0.0
        arm: "left"
        check_pos: true
      "9":
        description: "put the piston rod assembly on the table"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 2.0
        reach_target: [0.32,0.3,1.05] #[-0.2,0.4,1.05]
        end_delay: 0.0
        arm: "left"
        check_pos: true
      "10":
        description: "ensure the left arm is out of the way"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.8,-0.2,0.9] #[0.2,0.8,0.9]
        arm: "left"
        check_pos: false
      # "11":
      #   description: "ensure the right arm is out of the way"
      #   after_robot_task: 8
      #   after_human_task: -1
      #   start_delay: 0.0
      #   reach_target: [-0.2,0.8,-0.1]
      #   arm: "right"
      "11":
        description: "pick up connecting rod 2"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.1,0.39,1.05] #[-0.39,0.25,1.05]
        arm: "right"
        check_pos: true
      "12":
        description: "bring connecting rod 2 near to assembly area"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 2.0
        reach_target: [0.65,0.3,1.2] #[-0.3,0.65,1.2]
        arm: "right"
        check_pos: true
      "13":
        description: "ensure the left arm is out of the way"
        after_robot_task: 10
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.8,-0.2,0.9] #[0.2,0.8,0.9]
        arm: "left"
        check_pos: false
      "14":
        description: "place connecting rod 2 in piston after robot places piston"
        after_robot_task: 18
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.32,0.0,1.1] #[-0.0,0.4,1.1]
        arm: "right"
        check_pos: true
      "15":
        description: "rest right arm"
        after_robot_task: 18
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.8,0.2,0.9] #[-0.2,0.8,0.9]
        arm: "right"
        check_pos: false
      "16":
        description: "pick up pin 2"
        after_robot_task: 18
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.32,-0.35,1.00] #[0.2,0.5,1.00]
        end_delay: 0.0
        arm: "left"
        check_pos: true
      "17":
        description: "insert pin 2 through piston and rod"
        after_robot_task: 18
        after_human_task: -1
        start_delay: 2.0
        reach_target: [0.32,0.0,1.05] #[-0.0,0.4,1.05]
        end_delay: 0.0
        arm: "left"
        check_pos: true
      "18":
        description: "put the piston rod assembly 2 on the table"
        after_robot_task: 18
        after_human_task: -1
        start_delay: 2.0
        reach_target: [0.32,0.35,1.05] #[-0.2,0.4,1.05]
        end_delay: 0.0
        arm: "left"
        check_pos: true
      "19":
        description: "ensure the left arm is out of the way"
        after_robot_task: 18
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.8,-0.2,0.9] #[0.2,0.8,0.9]
        arm: "left"
        check_pos: false
      "20":
        description: "ensure the right arm is out of the way"
        after_robot_task: 18
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.8,0.2,0.9] #[-0.2,0.8,0.9]
        arm: "right"
        check_pos: false
  "2":
    add_collision_box: false
    workcell_transform: [0.0,0.0,1.0,0.707,0,0,-0.707]
    planning_time: 7.0
    robot_positions:
      length: 1
      "0": [0.4,0.0,0.11,0.000273793,-0.382499,0.923956,-0.000113345]
    robot_positions_at:
      length: 1
      "0": [0.000120783,-0.399879,1.11,0.000113495,0.382728,0.923861,-0.000273731]
    robot_poses:
      length: 1
      "0": [2.2995,-1.88062,2.0405,-1.73022,1.56967,-1.51353]
    robot_sequence:
      length: 2
      nonrestrictive_pipeline: irrt_avoid #irrt_avoid, dirrt, dirrt
      nonrestrictive_planner: irrta #irrta, dirrt_paper, multigoal_ssm_test
      "0":
        description: "open gripper"
        type: 2
        pct: 50
        after_human_task: -1
        start_delay: 0.0
      "1":
        description: "go to start position"
        type: 0
        goal: 0
        after_human_task: -1
        start_delay: 0.0
        pipeline: irrt_avoid
        planner: irrta
        use_nonrestrictive_planner: true
    human_sequence:
      length: 2
      start_pose: []  
      simulated_switch_times: [0.0]  
      show_human_rate: 50
      "0":
        description: "right arm start pose"
        after_robot_task: 0
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.8,0.2,0.9] #[-0.2,0.8,0.9]
        arm: "right"
        check_pos: false
      "1":
        description: "left arm start pose"
        after_robot_task: 0
        after_human_task: -1
        start_delay: 0.0
        reach_target: [0.8,-0.2,0.9] #[0.2,0.8,0.9]
        arm: "left"
        check_pos: false