home_joint: [1.5707963267949, -2.44346095279206, 2.44346095279206,-1.5707963267949, 1.5707963267949, 0]
tests:
  workcell_transform: [0.0,0.0,1.0,0.707,0,0,-0.707]
  human_start_pose: [0.9,0.0,0.965214,0.705906,-0.035458,0.0493738,-0.705692,0.677521,-0.0379904,-0.28419,-0.677316,0.503807,0.609008,0.34874,-0.503655,0.201172,-0.571943,-0.769392,-0.201111,0.501976,0.703839,0.0283315,-0.501825,0.201097,0.370572,0.884207,-0.201036,0.505554,-0.261435,-0.648565,-0.505401]
  "1":
    planning_pipeline: irrt_avoid
    planner_id: irrta
    human_task_num: 1
    robot_start: [-0.313824,-1.82125,2.06691,-1.79899,1.5707,1.88502] #start joint angles in degrees [-0.313824,-1.82125,2.06691,-1.79899,1.5707,1.88502]
    robot_goal: [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069] #stop joint angles in degrees [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069]
    log_file_name: avoid_task1
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    human_sequence_num: 0
    workcell_transform: [0.1,-0.1,1.0,0.707,0,0,-0.707]

  "2":
    planning_pipeline: ompl
    planner_id: BiTRRT
    human_task_num: 1
    robot_start: [-0.313824,-1.82125,2.06691,-1.79899,1.5707,1.88502] #start joint angles in degrees [-0.313824,-1.82125,2.06691,-1.79899,1.5707,1.88502]
    robot_goal: [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069] #stop joint angles in degrees [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069]
    log_file_name: birrt_task1
    use_collision_objects_initially: true
    use_collision_objects_continuously: false
    human_sequence_num: 0
    workcell_transform: [0.1,-0.2,1.0,0.707,0,0,-0.707]

  "3":
    planning_pipeline: dirrt
    planner_id: dirrt_paper
    human_task_num: 1
    robot_start: [-0.313824,-1.82125,2.06691,-1.79899,1.5707,1.88502] #start joint angles in degrees [-0.313824,-1.82125,2.06691,-1.79899,1.5707,1.88502]
    robot_goal: [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069] #stop joint angles in degrees [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069]
    log_file_name: dirrt_task1
    use_collision_objects_initially: true
    use_collision_objects_continuously: true
    human_sequence_num: 0
    workcell_transform: [0.1,-0.2,1.0,0.707,0,0,-0.707]

  "4":
    planning_pipeline: ompl
    planner_id: BiTRRT
    human_task_num: 1
    robot_start: [-0.313824,-1.82125,2.06691,-1.79899,1.5707,1.88502] #start joint angles in degrees [-0.313824,-1.82125,2.06691,-1.79899,1.5707,1.88502]
    robot_goal: [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069] #stop joint angles in degrees [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069]
    log_file_name: birrt_replan_task1
    use_collision_objects_initially: true
    use_collision_objects_continuously: true
    human_sequence_num: 0
    workcell_transform: [0.1,-0.2,1.0,0.707,0,0,-0.707]

  "5":
    planning_pipeline: dirrt
    planner_id: multigoal_ssm_test
    human_task_num: 1
    robot_start: [-0.313824,-1.82125,2.06691,-1.79899,1.5707,1.88502] #start joint angles in degrees [-0.313824,-1.82125,2.06691,-1.79899,1.5707,1.88502]
    robot_goal: [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069] #stop joint angles in degrees [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069]
    log_file_name: prob_hamp_task1
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    planning_time: 10
    human_sequence_num: 0
    workcell_transform: [0.1,-0.2,1.0,0.707,0,0,-0.707]

  "6":
    planning_pipeline: irrt_avoid
    planner_id: irrta
    human_task_num: 2
    robot_start: [2.89355,-1.81631,1.97772,-1.73246,1.5711,0.249443] #start joint angles in degrees [2.89355,-1.81631,1.97772,-1.73246,1.5711,0.249443]
    robot_goal: [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496] #stop joint angles in degrees [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496]
    log_file_name: avoid_task3
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    human_sequence_num: 1
    workcell_transform: [0.0,-0.1,1.0,0.707,0,0,-0.707]

  "7":
    planning_pipeline: ompl
    planner_id: BiTRRT
    human_task_num: 2
    robot_start: [2.89355,-1.81631,1.97772,-1.73246,1.5711,0.249443] #start joint angles in degrees
    robot_goal: [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496] #stop joint angles in degrees
    log_file_name: birrt_task3
    use_collision_objects_initially: true
    use_collision_objects_continuously: false
    human_sequence_num: 1
    workcell_transform: [0.0,-0.0,1.0,0.707,0,0,-0.707]

  "8":
    planning_pipeline: dirrt
    planner_id: dirrt_paper
    human_task_num: 2
    robot_start: [2.89355,-1.81631,1.97772,-1.73246,1.5711,0.249443] #start joint angles in degrees
    robot_goal: [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496] #stop joint angles in degrees
    log_file_name: dirrt_task3
    use_collision_objects_initially: true
    use_collision_objects_continuously: true
    human_sequence_num: 1
    workcell_transform: [0.0,-0.0,1.0,0.707,0,0,-0.707]

  "9":
    planning_pipeline: ompl
    planner_id: BiTRRT
    human_task_num: 2
    robot_start: [2.89355,-1.81631,1.97772,-1.73246,1.5711,0.249443] #start joint angles in degrees
    robot_goal: [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496] #stop joint angles in degrees
    log_file_name: birrt_replan_task3
    use_collision_objects_initially: true
    use_collision_objects_continuously: true
    human_sequence_num: 1
    workcell_transform: [0.0,-0.0,1.0,0.707,0,0,-0.707]

  "10":
    planning_pipeline: dirrt
    planner_id: multigoal_ssm_test
    human_task_num: 2
    robot_start: [2.89355,-1.81631,1.97772,-1.73246,1.5711,0.249443] #start joint angles in degrees
    robot_goal: [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496] #stop joint angles in degrees
    log_file_name: prob_hamp_task3
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    planning_time: 10
    human_sequence_num: 1
    workcell_transform: [0.0,-0.0,1.0,0.707,0,0,-0.707]
  "11":
    planning_pipeline: irrt_avoid
    planner_id: irrta
    human_task_num: 3
    robot_start: [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496] #start joint angles in degrees
    robot_goal: [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069] #stop joint angles in degrees
    log_file_name: avoid_gator_chomp
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    human_sequence_num: 2
    workcell_transform: [-0.2,-0.0,1.0,0.707,0,0,-0.707] #-0.1,-0.0,1.0,0.707,0,0,-0.707

  "12":
    planning_pipeline: ompl
    planner_id: BiTRRT
    human_task_num: 3
    robot_start: [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496] #start joint angles in degrees
    robot_goal: [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069] #stop joint angles in degrees
    log_file_name: birrt_gator_chomp
    use_collision_objects_initially: true
    use_collision_objects_continuously: false
    human_sequence_num: 2
    workcell_transform: [-0.1,-0.0,1.0,0.707,0,0,-0.707]

  "13":
    planning_pipeline: dirrt
    planner_id: dirrt_paper
    human_task_num: 3
    robot_start: [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496] #start joint angles in degrees
    robot_goal: [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069] #stop joint angles in degrees
    log_file_name: dirrt_gator_chomp
    use_collision_objects_initially: true
    use_collision_objects_continuously: true
    human_sequence_num: 2
    workcell_transform: [-0.1,-0.0,1.0,0.707,0,0,-0.707]

  "14":
    planning_pipeline: ompl
    planner_id: BiTRRT
    human_task_num: 3
    robot_start: [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496] #start joint angles in degrees
    robot_goal: [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069] #stop joint angles in degrees
    log_file_name: birrt_replan_gator_chomp
    use_collision_objects_initially: true
    use_collision_objects_continuously: true
    human_sequence_num: 2
    workcell_transform: [-0.1,-0.0,1.0,0.707,0,0,-0.707]

  "15":
    planning_pipeline: dirrt
    planner_id: multigoal_ssm_test
    human_task_num: 3
    robot_start: [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496] #start joint angles in degrees
    robot_goal: [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069] #stop joint angles in degrees
    log_file_name: prob_hamp_gator_chomp
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    planning_time: 10
    human_sequence_num: 2
    workcell_transform: [-0.1,-0.0,1.0,0.707,0,0,-0.707]

  "16":
    planning_pipeline: irrt_avoid
    planner_id: irrta2
    human_task_num: 1
    robot_start: [-0.313824,-1.82125,2.06691,-1.79899,1.5707,1.88502] #start joint angles in degrees [-0.313824,-1.82125,2.06691,-1.79899,1.5707,1.88502]
    robot_goal: [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069] #stop joint angles in degrees [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069]
    log_file_name: avoid2_task1
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    human_sequence_num: 0
    workcell_transform: [0.1,-0.2,1.0,0.707,0,0,-0.707]

  "17":
    planning_pipeline: irrt_avoid
    planner_id: irrta2
    human_task_num: 2
    robot_start: [2.89355,-1.81631,1.97772,-1.73246,1.5711,0.249443] #start joint angles in degrees [2.89355,-1.81631,1.97772,-1.73246,1.5711,0.249443]
    robot_goal: [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496] #stop joint angles in degrees [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496]
    log_file_name: avoid2_task3
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    human_sequence_num: 1
    workcell_transform: [0.0,-0.0,1.0,0.707,0,0,-0.707]

  "18":
    planning_pipeline: irrt_avoid
    planner_id: irrta2
    human_task_num: 0
    robot_start: [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496] #start joint angles in degrees
    robot_goal: [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069] #stop joint angles in degrees
    log_file_name: avoid2_gator_chomp
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    human_sequence_num: 2
    workcell_transform: [-0.1,-0.0,1.0,0.707,0,0,-0.707]

  "19":
    planning_pipeline: stomp
    planner_id: stomp
    human_task_num: 1
    robot_start: [-0.313824,-1.82125,2.06691,-1.79899,1.5707,1.88502] #start joint angles in degrees [-0.313824,-1.82125,2.06691,-1.79899,1.5707,1.88502]
    robot_goal: [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069] #stop joint angles in degrees [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069]
    log_file_name: stomp_task1
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    get_plan_time_from_perf: false
    human_sequence_num: 0
    planning_time: 10
    workcell_transform: [0.1,-0.2,1.0,0.707,0,0,-0.707]

  "20":
    planning_pipeline: stomp
    planner_id: stomp
    human_task_num: 2
    robot_start: [2.89355,-1.81631,1.97772,-1.73246,1.5711,0.249443] #start joint angles in degrees [2.89355,-1.81631,1.97772,-1.73246,1.5711,0.249443]
    robot_goal: [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496] #stop joint angles in degrees [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496]
    log_file_name: stomp_task3
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    get_plan_time_from_perf: false
    human_sequence_num: 1
    planning_time: 10
    workcell_transform: [0.0,-0.0,1.0,0.707,0,0,-0.707]

  "21":
    planning_pipeline: stomp
    planner_id: stomp
    human_task_num: 0
    robot_start: [0.507907,-1.28134,1.64746,-1.93558,1.5697,2.63496] #start joint angles in degrees
    robot_goal: [2.32584,-1.13013,1.43527,-1.87592,1.5715,0.817069] #stop joint angles in degrees
    log_file_name: stomp_gator_chomp
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    get_plan_time_from_perf: false
    human_sequence_num: 2
    workcell_transform: [-0.1,-0.0,1.0,0.707,0,0,-0.707]
