home_joint: [1.5707963267949, -2.44346095279206, 2.44346095279206,-1.5707963267949, 1.5707963267949, 0]
workcell_transform: [0.1,-0.2,1.0,0.707,0,0,-0.707]

tests:
  "1":
    planning_pipeline: irrt_avoid
    planner_id: irrta
    human_task_num: 1
    robot_start: [-18,-106,107,-90,90,108] #start joint angles in degrees [-18,-106,107,-90,90,108]
    robot_goal: [129, -67, 74, -97, 90, -39] #stop joint angles in degrees [129, -67, 74, -97, 90, -39]
    log_file_name: avoid_task1
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    human_sequence_num: 0
    workcell_transform: [0.1,-0.1,1.0,0.707,0,0,-0.707]

  "2":
    planning_pipeline: ompl
    planner_id: BiTRRT
    human_task_num: 1
    robot_start: [-18,-106,107,-90,90,108] #start joint angles in degrees [-18,-106,107,-90,90,108]
    robot_goal: [129, -67, 74, -97, 90, -39] #stop joint angles in degrees [129, -67, 74, -97, 90, -39]
    log_file_name: birrt_task1
    use_collision_objects_initially: true
    use_collision_objects_continuously: false
    human_sequence_num: 0
    workcell_transform: [0.1,-0.2,1.0,0.707,0,0,-0.707]

  "3":
    planning_pipeline: dirrt
    planner_id: dirrt_paper
    human_task_num: 1
    robot_start: [-18,-106,107,-90,90,108] #start joint angles in degrees [-18,-106,107,-90,90,108]
    robot_goal: [129, -67, 74, -97, 90, -39] #stop joint angles in degrees [129, -67, 74, -97, 90, -39]
    log_file_name: dirrt_task1
    use_collision_objects_initially: true
    use_collision_objects_continuously: true
    human_sequence_num: 0
    workcell_transform: [0.1,-0.2,1.0,0.707,0,0,-0.707]

  "4":
    planning_pipeline: ompl
    planner_id: BiTRRT
    human_task_num: 1
    robot_start: [-18,-106,107,-90,90,108] #start joint angles in degrees [-18,-106,107,-90,90,108]
    robot_goal: [129, -67, 74, -97, 90, -39] #stop joint angles in degrees [129, -67, 74, -97, 90, -39]
    log_file_name: birrt_replan_task1
    use_collision_objects_initially: true
    use_collision_objects_continuously: true
    human_sequence_num: 0
    workcell_transform: [0.1,-0.2,1.0,0.707,0,0,-0.707]

  "5":
    planning_pipeline: dirrt
    planner_id: multigoal_ssm_test
    human_task_num: 1
    robot_start: [-18,-106,107,-90,90,108] #start joint angles in degrees [-18,-106,107,-90,90,108]
    robot_goal: [129, -67, 74, -97, 90, -39] #stop joint angles in degrees [129, -67, 74, -97, 90, -39]
    log_file_name: prob_hamp_task1
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    planning_time: 5
    human_sequence_num: 0
    workcell_transform: [0.1,-0.2,1.0,0.707,0,0,-0.707]

  "6":
    planning_pipeline: irrt_avoid
    planner_id: irrta
    human_task_num: 2
    robot_start: [162,-90,95,-95,90,-72] #start joint angles in degrees [162,-90,95,-95,90,-72]
    robot_goal: [26,-64,66,-92,90,64] #stop joint angles in degrees [26,-64,66,-92,90,64]
    log_file_name: avoid_task3
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    human_sequence_num: 1
    workcell_transform: [0.0,-0.1,1.0,0.707,0,0,-0.707]

  "7":
    planning_pipeline: ompl
    planner_id: BiTRRT
    human_task_num: 2
    robot_start: [162,-90,95,-95,90,-72] #start joint angles in degrees
    robot_goal: [26,-64,66,-92,90,64] #stop joint angles in degrees
    log_file_name: birrt_task3
    use_collision_objects_initially: true
    use_collision_objects_continuously: false
    human_sequence_num: 1
    workcell_transform: [0.0,-0.0,1.0,0.707,0,0,-0.707]

  "8":
    planning_pipeline: dirrt
    planner_id: dirrt_paper
    human_task_num: 2
    robot_start: [162,-90,95,-95,90,-72] #start joint angles in degrees
    robot_goal: [26,-64,66,-92,90,64] #stop joint angles in degrees
    log_file_name: dirrt_task3
    use_collision_objects_initially: true
    use_collision_objects_continuously: true
    human_sequence_num: 1
    workcell_transform: [0.0,-0.0,1.0,0.707,0,0,-0.707]

  "9":
    planning_pipeline: ompl
    planner_id: BiTRRT
    human_task_num: 2
    robot_start: [162,-90,95,-95,90,-72] #start joint angles in degrees
    robot_goal: [26,-64,66,-92,90,64] #stop joint angles in degrees
    log_file_name: birrt_replan_task3
    use_collision_objects_initially: true
    use_collision_objects_continuously: true
    human_sequence_num: 1
    workcell_transform: [0.0,-0.0,1.0,0.707,0,0,-0.707]

  "10":
    planning_pipeline: dirrt
    planner_id: multigoal_ssm_test
    human_task_num: 2
    robot_start: [162,-90,95,-95,90,-72] #start joint angles in degrees
    robot_goal: [26,-64,66,-92,90,64] #stop joint angles in degrees
    log_file_name: prob_hamp_task3
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    planning_time: 5
    human_sequence_num: 1
    workcell_transform: [0.0,-0.0,1.0,0.707,0,0,-0.707]
  "11":
    planning_pipeline: irrt_avoid
    planner_id: irrta
    human_task_num: 3
    robot_start: [132,-52,60,-99,90,-42] #start joint angles in degrees
    robot_goal: [40,-75,79,-94,90,50] #stop joint angles in degrees
    log_file_name: avoid_gator_chomp
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    human_sequence_num: 2
    workcell_transform: [-0.2,-0.0,1.0,0.707,0,0,-0.707] #-0.1,-0.0,1.0,0.707,0,0,-0.707

  "12":
    planning_pipeline: ompl
    planner_id: BiTRRT
    human_task_num: 3
    robot_start: [132,-52,60,-99,90,-42] #start joint angles in degrees
    robot_goal: [40,-75,79,-94,90,50] #stop joint angles in degrees
    log_file_name: birrt_gator_chomp
    use_collision_objects_initially: true
    use_collision_objects_continuously: false
    human_sequence_num: 2
    workcell_transform: [-0.1,-0.0,1.0,0.707,0,0,-0.707]

  "13":
    planning_pipeline: dirrt
    planner_id: dirrt_paper
    human_task_num: 3
    robot_start: [132,-52,60,-99,90,-42] #start joint angles in degrees
    robot_goal: [40,-75,79,-94,90,50] #stop joint angles in degrees
    log_file_name: dirrt_gator_chomp
    use_collision_objects_initially: true
    use_collision_objects_continuously: true
    human_sequence_num: 2
    workcell_transform: [-0.1,-0.0,1.0,0.707,0,0,-0.707]

  "14":
    planning_pipeline: ompl
    planner_id: BiTRRT
    human_task_num: 3
    robot_start: [132,-52,60,-99,90,-42] #start joint angles in degrees
    robot_goal: [40,-75,79,-94,90,50] #stop joint angles in degrees
    log_file_name: birrt_replan_gator_chomp
    use_collision_objects_initially: true
    use_collision_objects_continuously: true
    human_sequence_num: 2
    workcell_transform: [-0.1,-0.0,1.0,0.707,0,0,-0.707]

  "15":
    planning_pipeline: dirrt
    planner_id: multigoal_ssm_test
    human_task_num: 3
    robot_start: [132,-52,60,-99,90,-42] #start joint angles in degrees
    robot_goal: [40,-75,79,-94,90,50] #stop joint angles in degrees
    log_file_name: prob_hamp_gator_chomp
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    planning_time: 5
    human_sequence_num: 2
    workcell_transform: [-0.1,-0.0,1.0,0.707,0,0,-0.707]

  "16":
    planning_pipeline: irrt_avoid
    planner_id: irrta2
    human_task_num: 1
    robot_start: [-18,-106,107,-90,90,108] #start joint angles in degrees [-18,-106,107,-90,90,108]
    robot_goal: [129, -67, 74, -97, 90, -39] #stop joint angles in degrees [129, -67, 74, -97, 90, -39]
    log_file_name: avoid2_task1
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    human_sequence_num: 0
    workcell_transform: [0.1,-0.2,1.0,0.707,0,0,-0.707]

  "17":
    planning_pipeline: irrt_avoid
    planner_id: irrta2
    human_task_num: 2
    robot_start: [162,-90,95,-95,90,-72] #start joint angles in degrees [162,-90,95,-95,90,-72]
    robot_goal: [26,-64,66,-92,90,64] #stop joint angles in degrees [26,-64,66,-92,90,64]
    log_file_name: avoid2_task3
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    human_sequence_num: 1
    workcell_transform: [0.0,-0.0,1.0,0.707,0,0,-0.707]

  "18":
    planning_pipeline: irrt_avoid
    planner_id: irrta2
    human_task_num: 0
    robot_start: [132,-52,60,-99,90,-42] #start joint angles in degrees
    robot_goal: [40,-75,79,-94,90,50] #stop joint angles in degrees
    log_file_name: avoid2_gator_chomp
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    human_sequence_num: 2
    workcell_transform: [-0.1,-0.0,1.0,0.707,0,0,-0.707]

  "19":
    planning_pipeline: stomp
    planner_id: stomp
    human_task_num: 1
    robot_start: [-18,-106,107,-90,90,108] #start joint angles in degrees [-18,-106,107,-90,90,108]
    robot_goal: [129, -67, 74, -97, 90, -39] #stop joint angles in degrees [129, -67, 74, -97, 90, -39]
    log_file_name: stomp_task1
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    get_plan_time_from_perf: false
    human_sequence_num: 0
    workcell_transform: [0.1,-0.2,1.0,0.707,0,0,-0.707]

  "20":
    planning_pipeline: stomp
    planner_id: stomp
    human_task_num: 2
    robot_start: [162,-90,95,-95,90,-72] #start joint angles in degrees [162,-90,95,-95,90,-72]
    robot_goal: [26,-64,66,-92,90,64] #stop joint angles in degrees [26,-64,66,-92,90,64]
    log_file_name: stomp_task3
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    get_plan_time_from_perf: false
    human_sequence_num: 1
    workcell_transform: [0.0,-0.0,1.0,0.707,0,0,-0.707]

  "21":
    planning_pipeline: stomp
    planner_id: stomp
    human_task_num: 0
    robot_start: [132,-52,60,-99,90,-42] #start joint angles in degrees
    robot_goal: [40,-75,79,-94,90,50] #stop joint angles in degrees
    log_file_name: stomp_gator_chomp
    use_collision_objects_initially: false
    use_collision_objects_continuously: false
    get_plan_time_from_perf: false
    human_sequence_num: 2
    workcell_transform: [-0.1,-0.0,1.0,0.707,0,0,-0.707]
