warp:
  repulsion: 0.0067 #.02
  attraction: 0.00
  table_repulsion: 0.01 #.02 
  smooth_steps: 2
  iterations: 2
  table_tolerance: 0.07
  connection_tol: 0.99
  cycle_time: 0.033 #.1
  direct_path_attraction: 0.0001
  connection_min_dist: 0.3
  goal_stop_tolerance: 0.7
  scale_jnt_ids: [3,4,5,8]